# Generated by Django 5.2.16 on 2026-07-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deuda_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='numero_cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
