# Generated by Django 5.2.16 on 2026-07-26 06:55

from django.db import migrations, models


def merge_financial_categories(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    MovimientoFinanciero = apps.get_model("core", "MovimientoFinanciero")
    Deuda = apps.get_model("core", "Deuda")

    financial_types = ["ingreso", "gasto", "deuda"]

    for categoria in Categoria.objects.filter(tipo__in=financial_types).order_by("usuario_id", "nombre", "id"):
        canonical = (
            Categoria.objects.filter(
                usuario_id=categoria.usuario_id,
                nombre=categoria.nombre,
                tipo="finanzas",
            )
            .exclude(pk=categoria.pk)
            .first()
        )

        if canonical:
            MovimientoFinanciero.objects.filter(categoria_id=categoria.pk).update(
                categoria_id=canonical.pk,
            )
            Deuda.objects.filter(categoria_id=categoria.pk).update(
                categoria_id=canonical.pk,
            )
            categoria.delete()
            continue

        duplicate = (
            Categoria.objects.filter(
                usuario_id=categoria.usuario_id,
                nombre=categoria.nombre,
                tipo__in=financial_types,
            )
            .exclude(pk=categoria.pk)
            .order_by("id")
            .first()
        )

        if duplicate and duplicate.pk < categoria.pk:
            MovimientoFinanciero.objects.filter(categoria_id=categoria.pk).update(
                categoria_id=duplicate.pk,
            )
            Deuda.objects.filter(categoria_id=categoria.pk).update(
                categoria_id=duplicate.pk,
            )
            categoria.delete()
            continue

        categoria.tipo = "finanzas"
        categoria.save(update_fields=["tipo"])


def restore_financial_categories(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    Categoria.objects.filter(tipo="finanzas").update(tipo="gasto")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deuda_numero_cuotas'),
    ]

    operations = [
        migrations.RunPython(merge_financial_categories, restore_financial_categories),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('finanzas', 'Finanzas')], max_length=20),
        ),
    ]
