# Generated by Django 5.2.16 on 2026-07-26 06:57

from django.db import migrations, models


def rename_finanzas_to_comun(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    Categoria.objects.filter(tipo="finanzas").update(tipo="comun")


def rename_comun_to_finanzas(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    Categoria.objects.filter(tipo="comun").update(tipo="finanzas")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_categoria_tipo'),
    ]

    operations = [
        migrations.RunPython(rename_finanzas_to_comun, rename_comun_to_finanzas),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('comun', 'Común')], max_length=20),
        ),
    ]
