# Generated by Django 5.2.16 on 2026-07-26 18:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='comprobante',
            field=models.FileField(blank=True, upload_to=core.models.movimiento_comprobante_path),
        ),
    ]
