# Generated by Django 5.2.16 on 2026-07-26 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movimientofinanciero_comprobante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("CREATE SCHEMA IF NOT EXISTS auditoria;", None)],
            reverse_sql=[("DROP SCHEMA IF EXISTS auditoria CASCADE;", None)],
        ),
        migrations.CreateModel(
            name='EliminacionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('objeto_id', models.CharField(max_length=80)),
                ('objeto_repr', models.CharField(max_length=255)),
                ('motivo_eliminacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de eliminación',
                'verbose_name_plural': 'registros de eliminación',
                'db_table': '"auditoria"."eliminacion_registro"',
                'ordering': ['-creado'],
            },
        ),
    ]
