# Generated by Django 5.2.16 on 2026-07-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_eliminacionregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='estado',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('eliminado', 'Eliminado')], default='confirmado', max_length=20),
        ),
    ]
