# Generated by Django 5.2.16 on 2026-07-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_comun_to_finanzas(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    Categoria.objects.filter(tipo="comun").update(tipo="finanzas")


def rename_finanzas_to_comun(apps, schema_editor):
    Categoria = apps.get_model("core", "Categoria")
    Categoria.objects.filter(tipo="finanzas").update(tipo="comun")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_movimientofinanciero_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoria',
            name='categoria_unica_por_usuario_tipo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoria'),
        ),
        migrations.RunPython(rename_comun_to_finanzas, rename_finanzas_to_comun),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('finanzas', 'Finanzas')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('usuario', 'nombre', 'tipo'), name='categoria_raiz_unica_por_usuario_tipo'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('usuario', 'parent', 'nombre', 'tipo'), name='subcategoria_unica_por_padre_usuario_tipo'),
        ),
    ]
