# Generated by Django 5.2.16 on 2026-07-26 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seed_default_financial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS finanzas;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], default='banco', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"finanzas"."cuenta_financiera"',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuentafinanciera'),
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"finanzas"."etiqueta"',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='core.etiqueta'),
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('otro', 'Otro')], default='transferencia', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"finanzas"."metodo_pago"',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metodopago'),
        ),
        migrations.CreateModel(
            name='MovimientoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=20)),
                ('concepto', models.CharField(max_length=160)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual')], default='mensual', max_length=20)),
                ('dia_mes', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('nota', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuentafinanciera')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"finanzas"."movimiento_recurrente"',
                'ordering': ['tipo', 'dia_mes', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"finanzas"."presupuesto_mensual"',
                'ordering': ['-anio', '-mes', 'categoria__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuentafinanciera',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='cuenta_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='etiqueta',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='etiqueta_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='metodopago',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='metodo_pago_unico_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='presupuestomensual',
            constraint=models.UniqueConstraint(fields=('usuario', 'categoria', 'anio', 'mes'), name='presupuesto_unico_por_categoria_mes'),
        ),
    ]
