# Generated by Django 5.2.16 on 2026-07-27 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assign_general_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.movimientorecurrente'),
        ),
        migrations.AddConstraint(
            model_name='movimientofinanciero',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrente__isnull', False)), fields=('usuario', 'recurrente', 'fecha'), name='movimiento_recurrente_unico_por_fecha'),
        ),
    ]
