# Generated by Django 5.2.16 on 2026-07-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_movimientofinanciero_recurrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodeuda',
            name='cuota_numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='pagodeuda',
            constraint=models.UniqueConstraint(condition=models.Q(('cuota_numero__isnull', False)), fields=('deuda', 'cuota_numero'), name='pago_deuda_unico_por_cuota'),
        ),
    ]
