# Generated by Django 5.2.16 on 2026-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_asignar_cuenta_prevista_a_recurrentes_pendientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='pago_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deuda',
            name='tasa_interes_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
