# Generated by Django 5.2.16 on 2026-09-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_deuda_pago_minimo_deuda_tasa_interes_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_usar_asistente_ia',
            field=models.BooleanField(default=False, verbose_name='Puede usar el asistente de IA'),
        ),
    ]
