# Generated by Django 5.2.16 on 2026-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_perfilusuario_puede_usar_asistente_ia'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS configuracion;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unico', models.BooleanField(default=True, editable=False, unique=True)),
                ('activo', models.BooleanField(default=False, verbose_name='Asistente activo')),
                ('proveedor', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq'), ('personalizado', 'Compatible con OpenAI')], default='gemini', max_length=30)),
                ('modelo', models.CharField(default='gemini-2.5-flash-lite', max_length=120)),
                ('url_base', models.URLField(default='https://generativelanguage.googleapis.com/v1beta/openai')),
                ('timeout_segundos', models.PositiveSmallIntegerField(default=25)),
                ('api_key_cifrada', models.TextField(blank=True, editable=False)),
                ('api_key_sufijo', models.CharField(blank=True, editable=False, max_length=8)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de IA',
                'verbose_name_plural': 'configuración de IA',
                'db_table': '"configuracion"."configuracion_ia"',
            },
        ),
    ]
