# Generated by Django 5.2.16 on 2026-10-04

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_ajustesaldo_movimiento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturaComprobante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.ImageField(upload_to=core.models.captura_comprobante_path)),
                ("estado", models.CharField(choices=[("cargada", "Cargada"), ("analizada", "Analizada"), ("borrador", "Borrador preparado"), ("confirmada", "Confirmada"), ("cancelada", "Cancelada"), ("error", "Revisión manual")], default="cargada", max_length=20)),
                ("datos_extraidos", models.JSONField(blank=True, default=dict)),
                ("error_analisis", models.CharField(blank=True, max_length=300)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("borrador", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="captura_comprobante", to="core.borradormovimientoia")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="capturas_comprobantes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": '"analisis"."captura_comprobante"', "ordering": ["-creado"]},
        ),
        migrations.CreateModel(
            name="ImportacionBancaria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo_nombre", models.CharField(max_length=255)),
                ("estado", models.CharField(choices=[("previsualizada", "Previsualizada"), ("confirmada", "Confirmada"), ("cancelada", "Cancelada")], default="previsualizada", max_length=20)),
                ("total_filas", models.PositiveIntegerField(default=0)),
                ("filas_duplicadas", models.PositiveIntegerField(default=0)),
                ("movimientos_creados", models.PositiveIntegerField(default=0)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("confirmado_en", models.DateTimeField(blank=True, null=True)),
                ("cuenta", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="importaciones_bancarias", to="core.cuentafinanciera")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="importaciones_bancarias", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": '"finanzas"."importacion_bancaria"', "ordering": ["-creado"]},
        ),
        migrations.CreateModel(
            name="LineaImportacionBancaria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_fila", models.PositiveIntegerField()),
                ("fecha", models.DateField()),
                ("concepto", models.CharField(max_length=160)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("huella", models.CharField(db_index=True, max_length=64)),
                ("duplicada", models.BooleanField(default=False)),
                ("importacion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lineas", to="core.importacionbancaria")),
                ("movimiento", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="linea_importacion", to="core.movimientofinanciero")),
            ],
            options={
                "db_table": '"finanzas"."linea_importacion_bancaria"',
                "ordering": ["numero_fila"],
                "constraints": [models.UniqueConstraint(fields=("importacion", "numero_fila"), name="linea_importacion_numero_unico")],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("vencimiento", "Vencimiento"), ("presupuesto", "Presupuesto"), ("saldo", "Saldo"), ("recomendacion", "Recomendación"), ("sistema", "Sistema")], default="sistema", max_length=24)),
                ("clave", models.CharField(blank=True, max_length=160)),
                ("titulo", models.CharField(max_length=160)),
                ("mensaje", models.CharField(max_length=300)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("leida", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("leida_en", models.DateTimeField(blank=True, null=True)),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notificaciones", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": '"usuarios"."notificacion"',
                "ordering": ["leida", "-creado"],
                "constraints": [models.UniqueConstraint(condition=~models.Q(clave=""), fields=("usuario", "clave"), name="notificacion_clave_unica_usuario")],
            },
        ),
    ]
