# Generated by Django 5.2.16 on 2026-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_perfilusuario_bienvenida_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='cuotas_pagadas_previas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
