# Generated by Django 5.2.16 on 2026-10-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_deuda_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unico', models.BooleanField(default=True, editable=False, unique=True)),
                ('activo', models.BooleanField(default=False, verbose_name='Usar esta configuración')),
                ('servidor', models.CharField(default='smtp.hostinger.com', max_length=255)),
                ('puerto', models.PositiveIntegerField(default=465)),
                ('usuario', models.EmailField(default='contacto@felixiot.site', max_length=254)),
                ('remitente', models.CharField(default='Félix IoT <contacto@felixiot.site>', help_text='Nombre y dirección que verán los destinatarios.', max_length=255)),
                ('destinatario_prueba', models.EmailField(blank=True, help_text='Dirección que recibirá el mensaje al ejecutar la prueba desde el administrador.', max_length=254)),
                ('usar_tls', models.BooleanField(default=False, verbose_name='Usar TLS/STARTTLS')),
                ('usar_ssl', models.BooleanField(default=True, verbose_name='Usar SSL')),
                ('timeout_segundos', models.PositiveSmallIntegerField(default=15)),
                ('password_cifrada', models.TextField(blank=True, editable=False)),
                ('password_configurada', models.BooleanField(default=False, editable=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de correo',
                'verbose_name_plural': 'configuración de correo',
                'db_table': '"configuracion"."configuracion_correo"',
            },
        ),
    ]
