# Generated by Django 5.2.16 on 2026-10-07 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_configuracioncorreo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada')], default='pendiente', max_length=20)),
                ('solicitada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_registro_resueltas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de registro',
                'verbose_name_plural': 'solicitudes de registro',
                'db_table': '"usuarios"."solicitud_registro"',
                'ordering': ['-solicitada_en'],
            },
        ),
    ]
