import calendar
from datetime import datetime, time
from decimal import Decimal, ROUND_HALF_UP

from django.db import IntegrityError, transaction
from django.db.models import Sum
from django.utils import timezone

from .models import (
    Acreedor,
    Categoria,
    CuentaFinanciera,
    Deuda,
    MetodoPago,
    MovimientoFinanciero,
    MovimientoRecurrente,
    PagoDeuda,
)


@transaction.atomic
def sincronizar_deuda_compra_credito(movimiento):
    """Create or keep in sync the payable generated by a credit-card purchase."""
    es_compra_credito = (
        movimiento.estado == MovimientoFinanciero.Estado.CONFIRMADO
        and movimiento.tipo == MovimientoFinanciero.Tipo.GASTO
        and movimiento.metodo_pago_id
        and movimiento.metodo_pago.tipo == MetodoPago.Tipo.CREDITO
        and movimiento.fecha_pago
        and movimiento.acreedor_credito_id
    )
    deuda = Deuda.objects.filter(movimiento_origen=movimiento).first()

    if not es_compra_credito:
        if deuda:
            if deuda.pagos.filter(estado=PagoDeuda.Estado.CONFIRMADO).exists():
                deuda.estado = Deuda.Estado.CANCELADA
                deuda.save(update_fields=["estado"])
            else:
                deuda.delete()
        return None

    acreedor = movimiento.acreedor_credito
    numero_cuotas = max(1, movimiento.numero_cuotas_credito)
    monto_movimiento = Decimal(movimiento.monto)
    fecha_ultima_cuota = sumar_meses(movimiento.fecha_pago, numero_cuotas - 1)
    if deuda is None:
        deuda = Deuda.objects.create(
            usuario=movimiento.usuario,
            movimiento_origen=movimiento,
            categoria=movimiento.categoria,
            acreedor=acreedor.nombre,
            acreedor_entidad=acreedor,
            concepto=movimiento.concepto,
            monto_inicial=movimiento.monto,
            saldo_actual=movimiento.monto,
            numero_cuotas=numero_cuotas,
            fecha_inicio=movimiento.fecha,
            fecha_primera_cuota=movimiento.fecha_pago,
            fecha_vencimiento=fecha_ultima_cuota,
            nota="Generada automáticamente desde una compra con tarjeta de crédito.",
        )
    elif not deuda.pagos.filter(estado=PagoDeuda.Estado.CONFIRMADO).exists():
        deuda.categoria = movimiento.categoria
        deuda.acreedor = acreedor.nombre
        deuda.acreedor_entidad = acreedor
        deuda.concepto = movimiento.concepto
        deuda.monto_inicial = movimiento.monto
        deuda.saldo_actual = movimiento.monto
        deuda.fecha_inicio = movimiento.fecha
        deuda.fecha_primera_cuota = movimiento.fecha_pago
        deuda.numero_cuotas = numero_cuotas
        deuda.fecha_vencimiento = fecha_ultima_cuota
        deuda.estado = Deuda.Estado.ACTIVA
        deuda.save()

    if not deuda.pagos.filter(estado=PagoDeuda.Estado.CONFIRMADO).exists():
        deuda.pagos.all().delete()
        monto_base = (monto_movimiento / Decimal(numero_cuotas)).quantize(
            Decimal("0.01"),
            rounding=ROUND_HALF_UP,
        )
        acumulado = Decimal("0")
        for cuota_numero in range(1, numero_cuotas + 1):
            monto_cuota = monto_base
            if cuota_numero == numero_cuotas:
                monto_cuota = monto_movimiento - acumulado
            PagoDeuda.objects.create(
                deuda=deuda,
                cuota_numero=cuota_numero,
                monto=monto_cuota,
                fecha=sumar_meses(movimiento.fecha_pago, cuota_numero - 1),
                estado=PagoDeuda.Estado.PENDIENTE,
                nota="Cuota de tarjeta generada desde el gasto a crédito.",
            )
            acumulado += monto_cuota
    return deuda


DEFAULT_FINANCIAL_CATEGORIES = [
    ("Comida", "#ef4444", ["Almuerzo", "Merienda", "Cena", "Restaurante", "Supermercado", "Café"]),
    ("Compras", "#38bdf8", ["Ropa", "Tecnología", "Hogar", "Regalos"]),
    ("Vivienda", "#f59e0b", ["Arriendo", "Servicios básicos", "Mantenimiento"]),
    ("Transporte", "#64748b", ["Bus", "Taxi", "Combustible", "Peaje"]),
    ("Vehículo", "#a855f7", ["Mantenimiento", "Parqueadero", "Seguro"]),
    ("Vida y entretenimiento", "#22c55e", ["Salud", "Deporte", "Ocio", "Suscripciones"]),
    ("Comunicación, PC", "#6366f1", ["Internet", "Celular", "Software", "Equipos"]),
    ("Ingresos", "#10b981", ["Salario", "Venta", "Freelance", "Intereses"]),
]


def generar_recomendaciones_financieras(
    *,
    ingresos,
    gastos,
    pagos_deuda,
    cuotas_proximas,
    saldo_deudas,
    gastos_categoria,
    gastos_recurrentes,
    movimientos_count,
    sin_categoria_count,
    presupuestos=None,
    deuda_prioritaria=None,
):
    """Return deterministic, explainable advice from registered financial data."""
    dinero = Decimal("0.01")
    ingresos = Decimal(ingresos)
    gastos = Decimal(gastos)
    pagos_deuda = Decimal(pagos_deuda)
    cuotas_proximas = Decimal(cuotas_proximas)
    saldo_deudas = Decimal(saldo_deudas)
    resultado = ingresos - gastos - pagos_deuda
    recomendaciones = []

    def agregar(prioridad, tipo, titulo, detalle, impacto=None, accion=""):
        recomendaciones.append(
            {
                "prioridad": prioridad,
                "tipo": tipo,
                "titulo": titulo,
                "detalle": detalle,
                "impacto": Decimal(impacto).quantize(dinero, rounding=ROUND_HALF_UP) if impacto is not None else None,
                "accion": accion,
            }
        )

    if movimientos_count == 0:
        agregar(
            10,
            "datos",
            "Registra movimientos para recibir recomendaciones",
            "No hay movimientos confirmados en el periodo. Sin una base real no es responsable sugerir recortes o metas.",
            accion="Registra ingresos y gastos con su fecha y categoría.",
        )
        return recomendaciones

    if not ingresos:
        agregar(
            10,
            "alerta",
            "Falta registrar ingresos",
            f"Hay {gastos:.2f} en gastos y {pagos_deuda:.2f} en pagos de deuda, pero ningún ingreso confirmado.",
            impacto=gastos + pagos_deuda,
            accion="Registra tus ingresos o define una fuente que cubra al menos ese importe.",
        )
    elif resultado < 0:
        faltante = abs(resultado)
        agregar(
            10,
            "alerta",
            "Cierra el déficit del periodo",
            f"Los gastos y pagos de deuda superan los ingresos en {faltante:.2f}.",
            impacto=faltante,
            accion=f"Reduce costos o aumenta ingresos en al menos {faltante:.2f} para llegar a equilibrio.",
        )
    else:
        meta_ahorro = (ingresos * Decimal("0.10")).quantize(dinero, rounding=ROUND_HALF_UP)
        if resultado >= meta_ahorro and meta_ahorro > 0:
            agregar(
                4,
                "oportunidad",
                "Aparta un ahorro automático",
                f"El resultado disponible de {resultado:.2f} permite separar el 10% de los ingresos sin quedar en déficit.",
                impacto=meta_ahorro,
                accion=f"Programa un ahorro de {meta_ahorro:.2f} después de recibir tus ingresos.",
            )
        elif meta_ahorro > resultado:
            brecha = meta_ahorro - resultado
            agregar(
                6,
                "mejora",
                "Construye margen para ahorrar",
                f"Para ahorrar el 10% de tus ingresos faltan {brecha:.2f} de margen en este periodo.",
                impacto=brecha,
                accion="Busca esa mejora entre gastos variables o ingresos adicionales.",
            )

    if ingresos:
        carga_actual = (gastos + pagos_deuda) / ingresos
        if carga_actual >= Decimal("0.80"):
            objetivo_costos = ingresos * Decimal("0.70")
            reduccion = max(Decimal("0"), gastos + pagos_deuda - objetivo_costos)
            agregar(
                9,
                "alerta" if carga_actual >= 1 else "mejora",
                "Reduce la presión sobre tus ingresos",
                f"Gastos y deuda consumen {carga_actual * Decimal('100'):.1f}% de los ingresos confirmados.",
                impacto=reduccion,
                accion=f"Un objetivo inicial es liberar {reduccion:.2f} para bajar la carga hacia el 70%.",
            )

        carga_proxima = cuotas_proximas / ingresos
        if cuotas_proximas and carga_proxima >= Decimal("0.30"):
            agregar(
                8,
                "deuda",
                "Prepara las próximas cuotas",
                f"Las cuotas registradas próximas equivalen al {carga_proxima * Decimal('100'):.1f}% de los ingresos del periodo.",
                impacto=cuotas_proximas,
                accion="Reserva primero las cuotas y evita añadir nuevas obligaciones hasta recuperar margen.",
            )

    if deuda_prioritaria and deuda_prioritaria.get("tasa_interes_anual"):
        tasa = Decimal(deuda_prioritaria["tasa_interes_anual"])
        minimo = deuda_prioritaria.get("pago_minimo")
        detalle_minimo = f" Su pago mínimo registrado es {Decimal(minimo):.2f}." if minimo is not None else ""
        agregar(
            9,
            "deuda",
            f"Prioriza {deuda_prioritaria['concepto']}",
            f"Es la deuda activa con mayor interés registrado ({tasa:.2f}% anual).{detalle_minimo}",
            impacto=deuda_prioritaria["saldo_actual"],
            accion="Cubre todas las cuotas mínimas y dirige cualquier abono adicional a esta deuda de mayor costo.",
        )

    if gastos_categoria and gastos > 0:
        principal = gastos_categoria[0]
        total_principal = Decimal(str(principal["total"]))
        concentracion = total_principal / gastos
        if concentracion >= Decimal("0.25"):
            ahorro_posible = total_principal * Decimal("0.10")
            agregar(
                7,
                "gasto",
                f"Revisa la categoría {principal['categoria']}",
                f"Concentra {concentracion * Decimal('100'):.1f}% del gasto ({total_principal:.2f}).",
                impacto=ahorro_posible,
                accion=f"Revisa sus movimientos: una mejora del 10% liberaría cerca de {ahorro_posible:.2f}.",
            )

    recurrentes = list(gastos_recurrentes)
    if recurrentes:
        total_recurrente = sum((Decimal(item.monto) for item in recurrentes), Decimal("0"))
        mayor = max(recurrentes, key=lambda item: item.monto)
        agregar(
            5,
            "recurrente",
            "Audita tus costos recurrentes",
            f"Hay {len(recurrentes)} costos activos por {total_recurrente:.2f} al mes; el mayor es {mayor.concepto} ({mayor.monto:.2f}).",
            impacto=total_recurrente * Decimal("0.10"),
            accion="Confirma que cada suscripción o servicio siga siendo necesario y renegocia el de mayor valor.",
        )

    excesos = [item for item in (presupuestos or []) if item["usado"] > item["presupuesto"]]
    if excesos:
        exceso_total = sum((item["usado"] - item["presupuesto"] for item in excesos), Decimal("0"))
        nombres = ", ".join(item["categoria"] for item in excesos[:3])
        agregar(
            8,
            "presupuesto",
            "Corrige categorías sobre presupuesto",
            f"{nombres} superan el límite definido por un total de {exceso_total:.2f}.",
            impacto=exceso_total,
            accion="Detén gastos no esenciales en esas categorías o ajusta el presupuesto si el límite ya no es realista.",
        )

    if sin_categoria_count:
        agregar(
            3,
            "datos",
            "Clasifica movimientos pendientes",
            f"Hay {sin_categoria_count} movimientos sin categoría; esto reduce la precisión del análisis por tipo de gasto.",
            accion="Asigna una categoría antes de tomar decisiones de recorte.",
        )

    if saldo_deudas and not any(item["tipo"] == "deuda" for item in recomendaciones):
        agregar(
            2,
            "deuda",
            "Mantén visible la deuda activa",
            f"El saldo pendiente registrado es {saldo_deudas:.2f}.",
            accion="Verifica fechas y montos de las cuotas para que la proyección permanezca actualizada.",
        )

    recomendaciones.sort(key=lambda item: item["prioridad"], reverse=True)
    return recomendaciones[:6]


@transaction.atomic
def ensure_user_finance_setup(user):
    """Provision the minimum useful workspace for every new or existing user."""
    for name, category_type, color in [
        ("General", CuentaFinanciera.Tipo.OTRO, "#64748b"),
        ("Efectivo", CuentaFinanciera.Tipo.EFECTIVO, "#22c55e"),
    ]:
        CuentaFinanciera.objects.get_or_create(
            usuario=user,
            nombre=name,
            defaults={"tipo": category_type, "color": color},
        )

    for name, payment_type in [
        ("Efectivo", MetodoPago.Tipo.EFECTIVO),
        ("Transferencia", MetodoPago.Tipo.TRANSFERENCIA),
        ("Débito", MetodoPago.Tipo.DEBITO),
        ("Crédito", MetodoPago.Tipo.CREDITO),
    ]:
        MetodoPago.objects.get_or_create(
            usuario=user,
            nombre=name,
            defaults={"tipo": payment_type},
        )

    for name, color, children in DEFAULT_FINANCIAL_CATEGORIES:
        parent, _ = Categoria.objects.get_or_create(
            usuario=user,
            tipo=Categoria.Tipo.FINANZAS,
            parent=None,
            nombre=name,
            defaults={"color": color},
        )
        for child_name in ["General", *children]:
            Categoria.objects.get_or_create(
                usuario=user,
                tipo=Categoria.Tipo.FINANZAS,
                parent=parent,
                nombre=child_name,
                defaults={"color": parent.color or color},
            )


def fecha_recurrente_para_mes(anio, mes, dia_mes):
    ultimo_dia = calendar.monthrange(anio, mes)[1]
    return datetime(anio, mes, min(dia_mes, ultimo_dia)).date()


def siguiente_mes(anio, mes):
    if mes == 12:
        return anio + 1, 1
    return anio, mes + 1


def sumar_meses(fecha, meses):
    month_index = fecha.month - 1 + int(meses)
    anio = fecha.year + month_index // 12
    mes = month_index % 12 + 1
    dia = min(fecha.day, calendar.monthrange(anio, mes)[1])
    return fecha.replace(year=anio, month=mes, day=dia)


def fecha_cuota_deuda(deuda, cuota_numero):
    primera_cuota = deuda.fecha_primera_cuota or sumar_meses(deuda.fecha_inicio, 1)
    return sumar_meses(primera_cuota, cuota_numero - 1)


@transaction.atomic
def crear_historial_inicial_deuda(deuda, hasta_fecha=None):
    """Reconstruct confirmed installments from the opening and current balances.

    This is only used when a debt is first loaded into the system. It never
    changes ``saldo_actual`` because that balance already includes these
    historical payments.
    """
    hasta_fecha = hasta_fecha or timezone.localdate()
    deuda = Deuda.objects.select_for_update().get(pk=deuda.pk)
    if deuda.pagos.exists() or deuda.numero_cuotas < 1 or deuda.monto_inicial <= 0:
        return []

    total_pagado = max(Decimal("0"), deuda.monto_inicial - deuda.saldo_actual)
    if total_pagado <= 0:
        return []

    cuota_teorica = deuda.monto_inicial / Decimal(deuda.numero_cuotas)
    cuotas_por_saldo = int(
        (total_pagado / cuota_teorica).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
    )
    cuotas_vencidas = sum(
        fecha_cuota_deuda(deuda, numero) <= hasta_fecha
        for numero in range(1, deuda.numero_cuotas + 1)
    )
    cuotas_pagadas = min(deuda.numero_cuotas, cuotas_vencidas, cuotas_por_saldo)
    if cuotas_pagadas <= 0:
        return []

    monto_base = (total_pagado / Decimal(cuotas_pagadas)).quantize(
        Decimal("0.01"),
        rounding=ROUND_HALF_UP,
    )
    creados = []
    acumulado = Decimal("0")
    for numero in range(1, cuotas_pagadas + 1):
        monto = monto_base
        if numero == cuotas_pagadas:
            monto = total_pagado - acumulado
        pago = PagoDeuda.objects.create(
            deuda=deuda,
            monto=monto,
            fecha=fecha_cuota_deuda(deuda, numero),
            cuota_numero=numero,
            estado=PagoDeuda.Estado.CONFIRMADO,
            confirmado_en=timezone.now(),
            nota="Cuota historica reconstruida al registrar el saldo actual.",
        )
        creados.append(pago)
        acumulado += monto
    return creados


@transaction.atomic
def reprogramar_fechas_cuotas(deuda):
    """Align every numbered payment with the debt's current start date."""
    deuda = Deuda.objects.select_for_update().get(pk=deuda.pk)
    actualizados = []
    for pago in deuda.pagos.filter(cuota_numero__isnull=False):
        nueva_fecha = fecha_cuota_deuda(deuda, pago.cuota_numero)
        if pago.fecha == nueva_fecha:
            continue
        pago.fecha = nueva_fecha
        pago.save(update_fields=["fecha"])
        actualizados.append(pago)
    return actualizados


@transaction.atomic
def sincronizar_cuotas_pendientes_deuda(deuda):
    """Build the complete outstanding installment plan for a debt."""
    deuda = Deuda.objects.select_for_update().get(pk=deuda.pk)
    deuda.pagos.filter(
        estado=PagoDeuda.Estado.PENDIENTE,
        cuota_numero__isnull=False,
    ).delete()

    if deuda.estado != Deuda.Estado.ACTIVA or deuda.saldo_actual <= 0:
        return []

    cuotas_confirmadas = set(
        deuda.pagos.filter(
            estado=PagoDeuda.Estado.CONFIRMADO,
            cuota_numero__isnull=False,
        ).values_list("cuota_numero", flat=True)
    )
    numeros_pendientes = [
        numero
        for numero in range(1, deuda.numero_cuotas + 1)
        if numero not in cuotas_confirmadas
    ]
    if not numeros_pendientes:
        return []

    monto_base = (deuda.saldo_actual / Decimal(len(numeros_pendientes))).quantize(
        Decimal("0.01"),
        rounding=ROUND_HALF_UP,
    )
    creados = []
    acumulado = Decimal("0")
    for posicion, numero in enumerate(numeros_pendientes, start=1):
        monto = monto_base
        if posicion == len(numeros_pendientes):
            monto = deuda.saldo_actual - acumulado
        pago = PagoDeuda.objects.create(
            deuda=deuda,
            monto=monto,
            fecha=fecha_cuota_deuda(deuda, numero),
            cuota_numero=numero,
            estado=PagoDeuda.Estado.PENDIENTE,
            nota="Cuota programada según el plan de la deuda.",
        )
        creados.append(pago)
        acumulado += monto
    return creados


def iter_fechas_recurrentes_vencidas(recurrente, hasta_fecha):
    creado_local = timezone.localtime(recurrente.creado)
    anio = creado_local.year
    mes = creado_local.month

    while True:
        fecha = fecha_recurrente_para_mes(anio, mes, recurrente.dia_mes)
        if fecha > hasta_fecha:
            break

        vence_en = timezone.make_aware(
            datetime.combine(fecha, time.min),
            timezone.get_current_timezone(),
        )
        if vence_en > creado_local:
            yield fecha

        anio, mes = siguiente_mes(anio, mes)


def movimientos_recurrentes_programados(usuario, fecha_inicio, fecha_fin, tipo=None, categoria_id=None):
    recurrentes = MovimientoRecurrente.objects.filter(
        usuario=usuario,
        activo=True,
    ).select_related("categoria__parent", "cuenta", "metodo_pago")
    if tipo in {MovimientoFinanciero.Tipo.INGRESO, MovimientoFinanciero.Tipo.GASTO}:
        recurrentes = recurrentes.filter(tipo=tipo)
    if categoria_id:
        if isinstance(categoria_id, (list, tuple, set)):
            recurrentes = recurrentes.filter(categoria_id__in=categoria_id)
        else:
            recurrentes = recurrentes.filter(categoria_id=categoria_id)

    programados = []
    for recurrente in recurrentes:
        meses_confirmados = set(
            MovimientoFinanciero.objects.filter(
                usuario=usuario,
                estado=MovimientoFinanciero.Estado.CONFIRMADO,
                recurrente=recurrente,
                fecha__lte=fecha_fin,
            ).values_list("fecha__year", "fecha__month")
        )
        for fecha in iter_fechas_recurrentes_vencidas(recurrente, fecha_fin):
            if fecha < fecha_inicio or (fecha.year, fecha.month) in meses_confirmados:
                continue
            programados.append(
                {
                    "recurrente": recurrente,
                    "tipo": recurrente.tipo,
                    "categoria": recurrente.categoria,
                    "monto": recurrente.monto,
                    "fecha": fecha,
                }
            )

    return programados


def generar_movimientos_recurrentes(hasta_fecha=None, usuario=None):
    hasta_fecha = hasta_fecha or timezone.localdate()
    recurrentes = MovimientoRecurrente.objects.filter(activo=True).select_related(
        "usuario",
        "categoria",
        "cuenta",
        "metodo_pago",
    )
    if usuario is not None:
        recurrentes = recurrentes.filter(usuario=usuario)

    creados = []
    omitidos = 0

    for recurrente in recurrentes:
        for fecha in iter_fechas_recurrentes_vencidas(recurrente, hasta_fecha):
            if MovimientoFinanciero.objects.filter(
                usuario=recurrente.usuario,
                recurrente=recurrente,
                fecha__year=fecha.year,
                fecha__month=fecha.month,
            ).exists():
                omitidos += 1
                continue
            movimiento = MovimientoFinanciero(
                usuario=recurrente.usuario,
                tipo=recurrente.tipo,
                categoria=recurrente.categoria,
                cuenta=recurrente.cuenta,
                metodo_pago=recurrente.metodo_pago,
                recurrente=recurrente,
                concepto=recurrente.concepto,
                monto=recurrente.monto,
                fecha=fecha,
                nota=recurrente.nota,
                estado=(
                    MovimientoFinanciero.Estado.CONFIRMADO
                    if recurrente.aplicar_automaticamente and recurrente.cuenta_id
                    else MovimientoFinanciero.Estado.PENDIENTE
                ),
            )
            try:
                with transaction.atomic():
                    movimiento.save()
            except IntegrityError:
                omitidos += 1
                continue
            creados.append(movimiento)

    return creados, omitidos


def iter_cuotas_deuda_vencidas(deuda, hasta_fecha):
    creado_local = timezone.localtime(deuda.creado)
    cuotas_registradas = set(
        deuda.pagos.filter(cuota_numero__isnull=False).values_list("cuota_numero", flat=True)
    )
    pagos_manuales = deuda.pagos.filter(cuota_numero__isnull=True).count()

    for cuota_numero in range(pagos_manuales + 1, deuda.numero_cuotas + 1):
        if cuota_numero in cuotas_registradas:
            continue
        fecha = fecha_cuota_deuda(deuda, cuota_numero)
        if fecha > hasta_fecha:
            break

        vence_en = timezone.make_aware(
            datetime.combine(fecha, time.min),
            timezone.get_current_timezone(),
        )
        if vence_en > creado_local:
            yield cuota_numero, fecha


def generar_pagos_deudas(hasta_fecha=None, usuario=None):
    hasta_fecha = hasta_fecha or timezone.localdate()
    deudas = Deuda.objects.filter(
        estado=Deuda.Estado.ACTIVA,
        saldo_actual__gt=0,
    ).prefetch_related("pagos")
    if usuario is not None:
        deudas = deudas.filter(usuario=usuario)

    creados = []
    omitidos = 0

    for deuda in deudas:
        for cuota_numero, fecha in iter_cuotas_deuda_vencidas(deuda, hasta_fecha):
            try:
                with transaction.atomic():
                    deuda_actual = Deuda.objects.select_for_update().get(pk=deuda.pk)
                    if deuda_actual.estado != Deuda.Estado.ACTIVA or deuda_actual.saldo_actual <= 0:
                        break
                    if PagoDeuda.objects.filter(deuda=deuda_actual, cuota_numero=cuota_numero).exists():
                        omitidos += 1
                        continue

                    pendiente_programado = deuda_actual.pagos.filter(
                        estado=PagoDeuda.Estado.PENDIENTE,
                    ).aggregate(total=Sum("monto"))["total"] or Decimal("0")
                    saldo_por_programar = max(Decimal("0"), deuda_actual.saldo_actual - pendiente_programado)
                    cuotas_registradas = deuda_actual.pagos.count()
                    cuotas_restantes = max(1, deuda_actual.numero_cuotas - cuotas_registradas)
                    monto = (saldo_por_programar / Decimal(cuotas_restantes)).quantize(
                        Decimal("0.01"),
                        rounding=ROUND_HALF_UP,
                    )
                    monto = min(monto, saldo_por_programar)
                    if monto <= 0:
                        break
                    pago = PagoDeuda.objects.create(
                        deuda=deuda_actual,
                        monto=monto,
                        fecha=fecha,
                        cuota_numero=cuota_numero,
                        estado=PagoDeuda.Estado.PENDIENTE,
                        nota="Cuota programada automáticamente; pendiente de confirmación.",
                    )
            except IntegrityError:
                omitidos += 1
                continue
            creados.append(pago)

    return creados, omitidos


def generar_finanzas_automaticas(hasta_fecha=None, usuario=None):
    movimientos, movimientos_omitidos = generar_movimientos_recurrentes(
        hasta_fecha=hasta_fecha,
        usuario=usuario,
    )
    pagos, pagos_omitidos = generar_pagos_deudas(
        hasta_fecha=hasta_fecha,
        usuario=usuario,
    )
    return {
        "movimientos": movimientos,
        "movimientos_omitidos": movimientos_omitidos,
        "pagos_deuda": pagos,
        "pagos_deuda_omitidos": pagos_omitidos,
    }


def cuotas_deudas_programadas(usuario, fecha_inicio, fecha_fin, categoria_id=None):
    deudas = Deuda.objects.filter(
        usuario=usuario,
        estado=Deuda.Estado.ACTIVA,
        saldo_actual__gt=0,
    ).prefetch_related("pagos")
    if categoria_id:
        if isinstance(categoria_id, (list, tuple, set)):
            deudas = deudas.filter(categoria_id__in=categoria_id)
        else:
            deudas = deudas.filter(categoria_id=categoria_id)

    cuotas = []
    total = Decimal("0")

    for deuda in deudas:
        creado_local = timezone.localtime(deuda.creado)
        pagos = list(deuda.pagos.all())
        pagos_count = len(pagos)
        cuotas_registradas = {
            pago.cuota_numero for pago in pagos if pago.cuota_numero is not None
        }
        pagos_manuales = sum(pago.cuota_numero is None for pago in pagos)
        pendiente_programado = sum(
            (pago.monto for pago in pagos if pago.estado == PagoDeuda.Estado.PENDIENTE),
            Decimal("0"),
        )
        saldo_virtual = max(Decimal("0"), deuda.saldo_actual - pendiente_programado)

        for pago in pagos:
            if pago.cuota_numero and fecha_inicio <= pago.fecha <= fecha_fin:
                cuotas.append(
                    {
                        "deuda": deuda,
                        "cuota_numero": pago.cuota_numero,
                        "fecha": pago.fecha,
                        "monto": pago.monto,
                        "estado": pago.estado,
                    }
                )
                total += pago.monto

        for cuota_numero in range(pagos_manuales + 1, deuda.numero_cuotas + 1):
            if cuota_numero in cuotas_registradas:
                continue
            fecha = fecha_cuota_deuda(deuda, cuota_numero)
            vence_en = timezone.make_aware(
                datetime.combine(fecha, time.min),
                timezone.get_current_timezone(),
            )
            if vence_en <= creado_local:
                continue
            if fecha > fecha_fin:
                break

            cuotas_restantes = max(1, deuda.numero_cuotas - cuota_numero + 1)
            monto = (saldo_virtual / Decimal(cuotas_restantes)).quantize(
                Decimal("0.01"),
                rounding=ROUND_HALF_UP,
            )
            monto = min(monto, saldo_virtual)

            if fecha_inicio <= fecha <= fecha_fin:
                cuotas.append(
                    {
                        "deuda": deuda,
                        "cuota_numero": cuota_numero,
                        "fecha": fecha,
                        "monto": monto,
                        "estado": PagoDeuda.Estado.PENDIENTE,
                    }
                )
                total += monto

            saldo_virtual = max(Decimal("0"), saldo_virtual - monto)
            if saldo_virtual == Decimal("0"):
                break

    return cuotas, total
